export const LOCAL_API_PORT = process.env.EXPO_PUBLIC_API_PORT ?? "3501";
export const LOCAL_TRANSCRIBER_PORT =
	process.env.EXPO_PUBLIC_TRANSCRIBER_PORT ?? "8787";
export const LOCAL_FACEBOOK_MEDIA_BRIDGE_PORT =
	process.env.EXPO_PUBLIC_FACEBOOK_MEDIA_BRIDGE_PORT ?? "8790";
